version: '3'

services:
  datadb:
    restart: always
    image: "postgres:14-alpine"
    container_name: data_appsdb
    volumes:
        - .:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5437:5432"

  appdjango:
    container_name: appdjango
    restart: always
    build: .
    depends_on:
      - datadb
    env_file:
      - .env
    #command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py  makemigrations subscriptions  && python manage.py migrate subscriptions && python manage.py runserver 0.0.0.0:8000"
    # command: python manage.py runserver 0.0.0.0:8080 
    volumes:
      - .:/app/second
      - ./static:/app/second/static


  nginx:
    image: nginx:1.21
    restart: unless-stopped
    volumes:
      - ./dev/nginx:/etc/nginx/conf.d
      - ./static:/app/second/static
    depends_on:
      - appdjango
    ports:
     
    
      - "8000:8000"