version: '3'

services:
  datadb:
    restart: always
    image: "postgres:14-alpine"
    container_name: data_appsdb
    volumes:
        - .:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5437:5432"

  appdjango:
    restart: always
    build: .
    depends_on:
      - datadb
    env_file:
      - .env
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations subscriptions && python manage.py migrate  && gunicorn config.wsgi --bind 0.0.0.0:8000"
    #command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # command: python manage.py runserver 0.0.0.0:8080 
    volumes:
      - .:/app/second
      - ./static:/app/second/static

  nginx:
    image: nginx:1.17
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./static:/app/second/static
    depends_on:
      - appdjango
    ports:
      - "8080:8080"
      - "3000:3000"
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  