# Generated by Django 3.2.9 on 2021-11-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Номер телефона клиента')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email клиента')),
                ('prosmotr', models.BooleanField(default=False, help_text='просмотрена ли заявка?', verbose_name='Заявка просмотрена ')),
                ('obrabotka', models.BooleanField(default=False, help_text='Заявка обрабатона и в архиве?', verbose_name='Заявка закрыта')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
