# Generated by Django 3.2.9 on 2021-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='obrabotka_end',
            field=models.BooleanField(default=False, help_text='Заявка обрабатона и в архиве?', verbose_name='Заявка закрыта'),
        ),
        migrations.AddField(
            model_name='orders',
            name='obrabotka_scklad',
            field=models.BooleanField(default=False, help_text='Вещи по заявке на складе?', verbose_name='Уже на складе'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='obrabotka',
            field=models.BooleanField(default=False, help_text='обработана  ли заявка?', verbose_name='Заявка обработана '),
        ),
    ]
