# Generated by Django 3.2.9 on 2021-11-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20211111_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
    ]
