# Generated by Django 3.2.9 on 2021-11-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_orders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.TextField(help_text='тип вещей указынный клиентом', max_length=1000, null=True, verbose_name='Указан тип вещей'),
        ),
    ]
