# Generated by Django 3.2.9 on 2021-11-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_orders_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Номер телефона клиента')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email клиента')),
                ('message', models.TextField(help_text='сообщение от клиента', max_length=1000, null=True, verbose_name='сообщение от клиента')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Заявку на сотрудничество',
                'verbose_name_plural': 'Заявки на сотрудничество',
            },
        ),
    ]
