# Generated by Django 3.2.9 on 2021-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20211205_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_succes',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата когда нужно забрать вещи'),
        ),
    ]
