# Generated by Django 3.2.9 on 2021-11-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='prosmotr',
            field=models.BooleanField(default=False, help_text='просмотрена ли заявка?', verbose_name='Заявка просмотрена '),
        ),
    ]
