# Generated by Django 3.2.9 on 2021-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_orders_typevesch'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Менеджер для этой заявки'),
        ),
    ]
