# Generated by Django 3.2.9 on 2021-11-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_works_prosmotr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('message_text', models.TextField(help_text='сообщение от клиента', max_length=1000, null=True, verbose_name='сообщение от клиента')),
                ('moderation', models.BooleanField(default=False, help_text='Комментарий допущен?', verbose_name='Комментарий допущен?')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
