# Generated by Django 3.2.9 on 2021-11-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('message_text', models.TextField(help_text='сообщение от клиента', max_length=1000, null=True, verbose_name='сообщение от клиента')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер клиента')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания комментария')),
                ('prosmotr', models.BooleanField(default=False, help_text='просмотрена ли заявка?', verbose_name='Заявка просмотрена ')),
            ],
            options={
                'verbose_name': 'Хочу в команду',
                'verbose_name_plural': 'Хотят в команду',
            },
        ),
    ]
