# Generated by Django 3.2.9 on 2021-12-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_typesitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='typevesch',
            field=models.ManyToManyField(blank=True, related_name='order_element', to='subscriptions.TypesItem', verbose_name='Вещи в заявке'),
        ),
    ]
