# Generated by Django 3.2.9 on 2021-12-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_orders_typevesch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес клиента'),
        ),
    ]
