# Generated by Django 3.2.9 on 2021-12-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20211208_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='typevesch',
        ),
        migrations.AddField(
            model_name='orders',
            name='itogprice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена вещей итого'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.TextField(blank=True, help_text='список вещей указынный клиентом', max_length=1000, null=True, verbose_name='Список вещей'),
        ),
    ]
