# Generated by Django 3.2.9 on 2021-12-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_auto_20211208_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypesItem',
        ),
    ]
