# Generated by Django 3.2.9 on 2021-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_auto_20211208_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont',
            name='counts',
            field=models.IntegerField(default=0, verbose_name=' Количество посещений'),
        ),
    ]
