# Generated by Django 3.2.9 on 2021-12-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_alter_cont_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя дата и время посещения'),
        ),
    ]
